import type { Employee, Correction, Shift, AttendanceLog, ProcessedAttendance } from './types';

export const employees: Employee[] = [
  {
    id: '1',
    name: 'Dr. Elara Vance',
    avatarUrl: 'https://picsum.photos/seed/1/100/100',
    department: 'Cardiologie',
    latenessRisk: 'Élevé',
    historicalAttendanceData: 'Souvent en retard le lundi, arrivée moyenne à 8h15 pour un début à 8h00. Arrivées tardives fréquentes après les jours fériés.',
  },
  {
    id: '2',
    name: 'Infirmier Kai Tanaka',
    avatarUrl: 'https://picsum.photos/seed/2/100/100',
    department: 'Pédiatrie',
    latenessRisk: 'Faible',
    historicalAttendanceData: 'Constamment à l\'heure. Aucun retard enregistré au cours des 6 derniers mois.',
  },
  {
    id: '3',
    name: 'Admin Zara Ahmed',
    avatarUrl: 'https://picsum.photos/seed/3/100/100',
    department: 'Administration',
    latenessRisk: 'Moyen',
    historicalAttendanceData: 'Retards occasionnels (1-2 fois par mois), généralement de 5 à 10 minutes. Corrélation avec les jours de forte circulation.',
  },
  {
    id: '4',
    name: 'Dr. Leo Martinez',
    avatarUrl: 'https://picsum.photos/seed/4/100/100',
    department: 'Orthopédie',
    latenessRisk: 'Faible',
    historicalAttendanceData: 'Excellent dossier de présence. Toujours ponctuel.',
  },
  {
    id: '5',
    name: 'Infirmière Maya Singh',
    avatarUrl: 'https://picsum.photos/seed/5/100/100',
    department: 'Urgences',
    latenessRisk: 'Élevé',
    historicalAttendanceData: 'Schéma de retard pour les gardes de nuit, en moyenne 20 minutes de retard. 3 cas le mois dernier.',
  },
  {
    id: '6',
    name: 'Chirurgien Ben Carter',
    avatarUrl: 'https://picsum.photos/seed/6/100/100',
    department: 'Chirurgie',
    latenessRisk: 'Moyen',
    historicalAttendanceData: 'A tendance à être en retard les jours suivant une longue garde. Retard moyen de 15 minutes.',
  },
];

export const corrections: Correction[] = [
    {
        id: 'corr1',
        adminName: 'Responsable RH',
        adminAvatarUrl: 'https://picsum.photos/seed/admin/100/100',
        employeeName: 'Dr. Elara Vance',
        date: new Date('2023-11-15T00:00:00.000Z'),
        reason: 'A oublié de badger en partant après la garde du matin.',
        timestamp: new Date('2023-11-15T17:05:00.000Z'),
    },
    {
        id: 'corr2',
        adminName: 'Responsable RH',
        adminAvatarUrl: 'https://picsum.photos/seed/admin/100/100',
        employeeName: 'Infirmière Maya Singh',
        date: new Date('2023-11-14T00:00:00.000Z'),
        reason: 'Dysfonctionnement du lecteur biométrique.',
        timestamp: new Date('2023-11-14T09:30:00.000Z'),
    },
     {
        id: 'corr3',
        adminName: 'Responsable RH',
        adminAvatarUrl: 'https://picsum.photos/seed/admin/100/100',
        employeeName: 'Chirurgien Ben Carter',
        date: new Date('2023-11-13T00:00:00.000Z'),
        reason: 'Chirurgie d\'urgence prolongée au-delà des heures de garde, ajustement manuel requis.',
        timestamp: new Date('2023-11-13T23:00:00.000Z'),
    }
];

export const shifts: Shift[] = [
  { id: 's1', employeeId: '1', date: new Date(), shiftType: 'Matin' },
  { id: 's2', employeeId: '2', date: new Date(), shiftType: 'Journée Complète' },
  { id: 's3', employeeId: '3', date: new Date(), shiftType: 'Repos' },
  { id: 's4', employeeId: '4', date: new Date(), shiftType: 'Garde de Nuit' },
  { id: 's5', employeeId: '5', date: new Date(), shiftType: 'Matin' },
  { id: 's6', employeeId: '6', date: new Date(), shiftType: 'Journée Complète' },
];

export const attendanceLogs: AttendanceLog[] = [
    {
        id: 'log1',
        dateTime: '2025-07-31 17:40:10',
        personnelId: '24',
        firstName: 'Tome',
        lastName: '',
        cardNumber: '',
        deviceName: 'MIARAKA',
        eventPoint: 'MIARAKA-1',
        verifyType: 'Only Face',
        inOutStatus: 'Check-In',
        eventDescription: 'Normal Punch Open',
        remarks: '.',
        createdAt: new Date() as any,
    },
    {
        id: 'log2',
        dateTime: '2025-07-31 17:35:05',
        personnelId: '5',
        firstName: 'Maya',
        lastName: 'Singh',
        cardNumber: 'C005',
        deviceName: 'MIARAKA',
        eventPoint: 'URGENCES-1',
        verifyType: 'Face+Card',
        inOutStatus: 'Check-In',
        eventDescription: 'Normal Punch Open',
        remarks: '.',
        createdAt: new Date() as any,
    },
    {
        id: 'log3',
        dateTime: '2025-07-31 12:05:21',
        personnelId: '2',
        firstName: 'Kai',
        lastName: 'Tanaka',
        cardNumber: 'C002',
        deviceName: 'MIARAKA',
        eventPoint: 'PEDIATRIE-1',
        verifyType: 'Only Face',
        inOutStatus: 'Check-Out',
        eventDescription: 'Normal Punch Open',
        remarks: 'Départ déjeuner',
        createdAt: new Date() as any,
    },
    {
        id: 'log4',
        dateTime: '2025-07-31 08:05:15',
        personnelId: '1',
        firstName: 'Elara',
        lastName: 'Vance',
        cardNumber: 'C001',
        deviceName: 'MIARAKA',
        eventPoint: 'CARDIO-1',
        verifyType: 'Only Face',
        inOutStatus: 'Check-In',
        eventDescription: 'Normal Punch Open',
        remarks: '5 min en retard',
        createdAt: new Date() as any,
    }
]

export const processedAttendanceData: ProcessedAttendance[] = [
    {
        id: 'pa1',
        employee_id: '1',
        employee_name: 'Dr. Elara Vance',
        date: '2023-07-31',
        morning_in: '08:05',
        morning_out: '12:02',
        afternoon_in: '14:00',
        afternoon_out: '18:03',
        total_worked_hours: 8.0,
        total_late_minutes: 5,
        total_overtime_minutes: 3,
        is_leave: false,
        leave_type: null,
    },
    {
        id: 'pa2',
        employee_id: '2',
        employee_name: 'Infirmier Kai Tanaka',
        date: '2023-07-31',
        morning_in: '07:58',
        morning_out: '12:05',
        afternoon_in: '13:55',
        afternoon_out: '18:00',
        total_worked_hours: 8.2,
        total_late_minutes: 0,
        total_overtime_minutes: 5,
        is_leave: false,
        leave_type: null,
    },
    {
        id: 'pa3',
        employee_id: '3',
        employee_name: 'Admin Zara Ahmed',
        date: '2023-07-31',
        morning_in: null,
        morning_out: null,
        afternoon_in: null,
        afternoon_out: null,
        total_worked_hours: 0,
        total_late_minutes: 0,
        total_overtime_minutes: 0,
        is_leave: true,
        leave_type: 'Congé Annuel',
    },
     {
        id: 'pa4',
        employee_id: '5',
        employee_name: 'Infirmière Maya Singh',
        date: '2023-07-31',
        morning_in: '08:20',
        morning_out: '12:15',
        afternoon_in: '14:05',
        afternoon_out: '18:10',
        total_worked_hours: 7.8,
        total_late_minutes: 25,
        total_overtime_minutes: 25,
        is_leave: false,
        leave_type: null,
    },
]
